In [1]:
import pandas as pd
import numpy as np

In [2]:
def load_weather(df):
    
    df = df.loc[:, ["STATION", "NAME", "LATITUDE", "LONGITUDE", "DATE", "PRCP", "WSF2", "WSF5"]]
    
    df["DATE"] = pd.to_datetime(df["DATE"])
    
    df.set_index("DATE", inplace=True)
    
    return df

### Atlantic City, New Jersey

In [3]:
acnj = pd.read_csv("./noaa-precip-wind-csv-data/atlantic-city-nj.csv")

acnj = load_weather(acnj)

acnj.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00013724,"ATLANTIC CITY MARINA, NJ US",39.37778,-74.42361,0.00,6.9,19.0
2010-01-02,USW00013724,"ATLANTIC CITY MARINA, NJ US",39.37778,-74.42361,0.00,14.1,34.9
2010-01-03,USW00013724,"ATLANTIC CITY MARINA, NJ US",39.37778,-74.42361,0.01,28.0,45.0
2010-01-04,USW00013724,"ATLANTIC CITY MARINA, NJ US",39.37778,-74.42361,0.00,10.1,25.1
2010-01-05,USW00013724,"ATLANTIC CITY MARINA, NJ US",39.37778,-74.42361,0.00,8.9,23.0

### Westerly State Airport, Washington County, Rhode Island

In [4]:
wcri = pd.read_csv("./noaa-precip-wind-csv-data/washington-county-ri.csv")

wcri = load_weather(wcri)

wcri.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00014794,"WESTERLY STATE AIRPORT, RI US",41.34972,-71.79889,0.04,8.9,10.1
2010-01-02,USW00014794,"WESTERLY STATE AIRPORT, RI US",41.34972,-71.79889,0.15,21.0,33.1
2010-01-03,USW00014794,"WESTERLY STATE AIRPORT, RI US",41.34972,-71.79889,0.00,23.0,36.9
2010-01-04,USW00014794,"WESTERLY STATE AIRPORT, RI US",41.34972,-71.79889,0.00,18.1,30.0
2010-01-05,USW00014794,"WESTERLY STATE AIRPORT, RI US",41.34972,-71.79889,0.00,10.1,18.1

### New Bedford, MA

In [5]:
nbma = pd.read_csv("./noaa-precip-wind-csv-data/new-bedford-ma.csv")

nbma = load_weather(nbma)

nbma.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00094726,"NEW BEDFORD MUNICIPAL AIRPORT, MA US",41.67639,-70.95833,0.02,8.1,10.1
2010-01-02,USW00094726,"NEW BEDFORD MUNICIPAL AIRPORT, MA US",41.67639,-70.95833,0.10,25.1,36.0
2010-01-03,USW00094726,"NEW BEDFORD MUNICIPAL AIRPORT, MA US",41.67639,-70.95833,0.00,29.1,38.0
2010-01-04,USW00094726,"NEW BEDFORD MUNICIPAL AIRPORT, MA US",41.67639,-70.95833,0.00,18.1,23.9
2010-01-05,USW00094726,"NEW BEDFORD MUNICIPAL AIRPORT, MA US",41.67639,-70.95833,0.00,12.1,16.1

### Boston, MA

In [6]:
boma = pd.read_csv("./noaa-precip-wind-csv-data/boston-ma.csv")

boma = load_weather(boma)

boma.head()

                STATION           NAME  LATITUDE  LONGITUDE  PRCP  WSF2  WSF5
DATE
2010-01-01  USW00014739  BOSTON, MA US   42.3606   -71.0097  0.00  15.0  19.9
2010-01-02  USW00014739  BOSTON, MA US   42.3606   -71.0097  0.43  30.0  38.0
2010-01-03  USW00014739  BOSTON, MA US   42.3606   -71.0097  0.20  31.1  40.9
2010-01-04  USW00014739  BOSTON, MA US   42.3606   -71.0097  0.00  23.0  31.1
2010-01-05  USW00014739  BOSTON, MA US   42.3606   -71.0097  0.00  17.0  23.9

### Bridgeport, CT

In [8]:
brct = pd.read_csv("./noaa-precip-wind-csv-data/bridgeport-ct.csv")

brct = load_weather(brct)

brct.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00094702,"IGOR I SIKORSKY MEMORI AIRPORT, CT US",41.1583,-73.1289,0.03,8.1,12.1
2010-01-02,USW00094702,"IGOR I SIKORSKY MEMORI AIRPORT, CT US",41.1583,-73.1289,0.06,25.9,34.9
2010-01-03,USW00094702,"IGOR I SIKORSKY MEMORI AIRPORT, CT US",41.1583,-73.1289,0.07,28.0,36.0
2010-01-04,USW00094702,"IGOR I SIKORSKY MEMORI AIRPORT, CT US",41.1583,-73.1289,0.00,19.9,23.9
2010-01-05,USW00094702,"IGOR I SIKORSKY MEMORI AIRPORT, CT US",41.1583,-73.1289,0.00,21.0,30.0

### New Haven, CT

In [9]:
nhct = pd.read_csv("./noaa-precip-wind-csv-data/new-haven-ct.csv")

nhct = load_weather(nhct)

nhct.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00014758,"NEW HAVEN TWEED AIRPORT, CT US",41.26389,-72.88722,0.02,8.1,10.1
2010-01-02,USW00014758,"NEW HAVEN TWEED AIRPORT, CT US",41.26389,-72.88722,0.00,21.9,38.0
2010-01-03,USW00014758,"NEW HAVEN TWEED AIRPORT, CT US",41.26389,-72.88722,0.00,25.1,38.0
2010-01-04,USW00014758,"NEW HAVEN TWEED AIRPORT, CT US",41.26389,-72.88722,0.00,17.0,28.0
2010-01-05,USW00014758,"NEW HAVEN TWEED AIRPORT, CT US",41.26389,-72.88722,0.00,16.1,23.9

### New London, CT

In [10]:
nlct = pd.read_csv("./noaa-precip-wind-csv-data/new-london-ct.csv")

nlct = load_weather(nlct)

nlct.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00014707,"GROTON NEW LONDON AIRPORT, CT US",41.3275,-72.04944,0.0,8.1,10.1
2010-01-02,USW00014707,"GROTON NEW LONDON AIRPORT, CT US",41.3275,-72.04944,0.0,31.1,40.9
2010-01-03,USW00014707,"GROTON NEW LONDON AIRPORT, CT US",41.3275,-72.04944,0.0,31.1,42.9
2010-01-04,USW00014707,"GROTON NEW LONDON AIRPORT, CT US",41.3275,-72.04944,0.0,21.0,28.0
2010-01-05,USW00014707,"GROTON NEW LONDON AIRPORT, CT US",41.3275,-72.04944,0.0,17.0,21.0

### Newport, RI

In [12]:
npri = pd.read_csv("./noaa-precip-wind-csv-data/newport-ri.csv")

npri = load_weather(npri)

npri.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00014787,"NEWPORT STATE AIRPORT, RI US",41.53333,-71.28333,0.0,13.0,16.1
2010-01-02,USW00014787,"NEWPORT STATE AIRPORT, RI US",41.53333,-71.28333,0.0,25.1,36.9
2010-01-03,USW00014787,"NEWPORT STATE AIRPORT, RI US",41.53333,-71.28333,0.0,28.0,38.9
2010-01-04,USW00014787,"NEWPORT STATE AIRPORT, RI US",41.53333,-71.28333,0.0,21.0,30.0
2010-01-05,USW00014787,"NEWPORT STATE AIRPORT, RI US",41.53333,-71.28333,0.0,16.1,21.9